### ISSUE TITLE
AJ Kerrigan - "Curiosity Before Judgement"

### ISSUE THREAD

**Issue by snuggs** [NYCrb/devpunks#17]
_"Curiosity before Judgement"_

Project Link: https://github.com/NYCrb/devpunks/projects/1#card-1886270

**Comment by snuggs** [comment]
![capture d ecran 2017-02-27 a 21 22 45](https://cloud.githubusercontent.com/assets/38223/23389217/b1e69d8c-fd34-11e6-909b-234781ecb68b.png)

**Comment by snuggs** [comment]
Really touched home literally with father sharing experience.

Let's round up some links for *?/!*. The world should know about this "code" :-)

**Comment by ajkerrigan** [comment]
Sure thing. I found a bunch as I was reading up and figuring out whether or not to go ahead with this idea :). First I'll link to the excellent [Legacy Code Rocks](http://legacycode.rocks) community. A simple "? / !" message in that team's Slack channel sparked all of this discussion, and put a label on something I've been inelegantly trying to practice and explain for years. "Curiosity before judgement" is an old concept that has no explicit ties to tech, and I can't take credit for any of this. It just happened to resonate with me so I'm happy to talk about it.

As for content links, I'll break them up into a few categories. First the psychology-focused ones:

- https://healthypsych.com/psychology-tools-more-curiosity-less-judgment/
- http://www.seattletimes.com/seattle-news/health/curiosity-not-judgment-leads-to-understanding/
- https://www.forbes.com/sites/shenegotiates/2012/11/30/change-your-life-in-2013-by-shifting-judgment-to-curiosity/
- https://coachcampus.com/coach-portfolios/power-tools/kenetha-j-stanton-curiosity-vs-judgment/

Then one example of a "Wait, why are we judging these people?" article with more of a tech focus:

- http://neilstudd.ghost.io/2015/06/06/whats-wrong-with-9-to-5-testers/

After reading that, I thought "I'd really like to see some positive stories about people consciously putting curiosity ahead of judgement" so I tried searching Medium for "I was wrong" and "I'm sorry". Tossing aside the inevitable snark posts, there were some honest reflections:

- https://blog.reifyworks.com/i-was-wrong-about-spreadsheets-and-im-sorry-59998ea8cefd#.cckr47k4q
- https://medium.com/@dillonforrest/sorry-developer-bootcamps-i-was-wrong-ea37fcc5572c#.1l1pfriuk
- https://medium.com/@The_Iron_Yuppie/i-was-wrong-about-a-lot-of-people-im-sorry-81c5a7eb13a8#.7bw6kfpcq

The last one is political, which I don't really want to touch. Still, you can't have a discussion like this without realizing how it relates to today's political climate and our Facebook/Twitter/etc feeds. And it does help highlight how rapid judgements are in part a coping mechanism for your overwhelmed brain. An inbox filter.

Some extra high-level points I don't want to lose track of:

- "Judgement" in this context doesn't just mean judging other people - it applies to judging yourself as well.
- "Curiosity *before judgement*" does not mean "*instead of* judgement". Judgement comes naturally for a reason. Sometimes you need to judge *now* and reflect later. Example: parental discipline.

We'll talk soon!

**Comment by snuggs** [comment]
DAYUMN! @ajkerrigan I was JUST thinking about this and look at you beasting out early! You never cease to amaze me.

**Comment by janz93** [comment]
I would love to geht a Chance to hear that talk as well.
@ajkerrigan maybe somewhere in Germany?

**Comment by ajkerrigan** [comment]
@janz93 This isn't going to be a conference talk, I'm expecting more of a 1-on-1 conversation with @snuggs. I think the goal is that through the magic of editing it can become a reasonably short and worthwhile podcast episode :).

**Comment by snuggs** [comment]
#FACTS @ajkerrigan I've setup a zencaster.com account for trial. Might wanna give 'er a test drive. /cc @janz93

**Comment by snuggs** [comment]
@ajkerrigan here https://www.youtube.com/watch?v=p73-30lE-XE

**Comment by snuggs** [comment]
@ajkerrigan ![image](https://media.giphy.com/media/4pMX5rJ4PYAEM/giphy.gif)

**Comment by snuggs** [comment]
@ajkerrigan care to drop a link on the how i met your mother? Honestly i've only seen one episode! Possibly a link relative to the show topic. And one that a HIMYM episode is a must see for a noob. :-)

**Comment by ajkerrigan** [comment]
This topic is covered well by the articles here and by more capable folks elsewhere. I don't have anything of value to add, but I can at least clean up a dangling open issue! :)

**Comment by snuggs** [comment]
Ah just got this @ajkerrigan was planning on seeing how you were in the channel. Was thinking of you. Haven't been in the channel in a while. I'll come check you out.

**Comment by ajkerrigan** [comment]
Hey @snuggs I feel like aborting this talk was the right call, but I left you hanging with that whole "glass-breaking" concept from How I Met Your Mother. It just so happens that the same idea came up in this excellent [QCon talk](https://www.infoq.com/presentations/communication-code-marriage) (reference comes around 19:30). Just in case you or anyone else following this thread is interested, check it out :).

**Comment by snuggs** [comment]
Wait a minute @ajkerrigan . So you mean to tell me that I thought of you while you were thinking of me? WOW!!!! 

P.S. I DO NOT believe it was a good idea aborting............. Now that I actually know how to fucking use Zencastr. Was placed in a recent situation where I HAD TO figure it out. Amazing what you are capable of when you have no alternatives.
