### ISSUE TITLE
What's in YOUR .tmux.conf? w/ Alex Piechowski

### ISSUE THREAD

**Issue by snuggs** [NYCrb/devpunks#22]
Let's jump on a hangout and yack shave. If we record it won't feel so bad. :-D @pachonk

Mine probably needs some refactoring as well! I like how light @pachonk's is.

Alex https://github.com/pachonk/config/blob/master/.tmux.conf
Snuggs https://gist.github.com/snuggs/800936

**Comment by pachonk** [comment]
Let me look through your tmux config when I'm free and then we can do a quick talk.

**Comment by snuggs** [comment]
Oh yes @pachonk This is what the `WIP` label is for. Let's have fun with it. OSS should be organic yes? /cc @mcantor may want some of this. ;-)

**Comment by pachonk** [comment]
@snuggs just a few comments I was able to whip together about your config:

- it seems you have WAY more than you need. I would recommend cutting this down to only what you need
- setting base index is super nice (https://github.com/pachonk/config/blob/master/.tmux.conf#L26)
- alt arrow (or alt vim keys) to move panes without using the prefix (https://github.com/pachonk/config/blob/master/.tmux.conf#L20)
- Have you checked out ZSH? It has a lot of built in PS-1's that include gitbranch
- tmux works best (imho) in urxvt because you can customize even a little more
- Do you really need aggressive-resize on your lappy?
- I forgot what I lost, but I found that I lost features with mouse mode
- I prefer to unbind directly above the key I make a new binding for, rather than unbinding in 1 block-

**Comment by snuggs** [comment]
@pachonk we can move forward on this. It's actually been requested at a couple past meetups. Looks like public issues working lol.

**Comment by pachonk** [comment]
Oh gawd, my entire config is different now I believe. Suhweet
