### ISSUE TITLE
Hiring Manager

### ISSUE THREAD

**Issue by snuggs** [NYCrb/devpunks#9]
![](https://pbs.twimg.com/media/CyVF8NpXAAAeYpM.jpg)

@wcpines @btakita @melaniegershman @arun1595 what do we think of this?

Do remember the concept is to have junior/senior devs and hiring managers to be more collaborative in the community. But as we know those definitions have to be changed a bit.

Open to suggestions as your input is just as valuable as mine.

**Comment by melaniegershman** [comment]
I think this is a great concept, the only bit missing might be to **encourage communication**. I think the hardest part about management sometimes can be managing miscommunication that happens amongst a team of different people that are meant to have the same goal. It goes hand in hand with what you mentioned re: increasing collaboration across teams.

**Comment by joyceschiffer** [comment]
I agree!  Here is the key to the kingdom. 'Communication'. We need to talk openly and ask the right questions. Career advice should be free and transparent. I love to talk to developers of all levels. I offer direction, encouragement and some insight into the hiring company.

**Comment by mcantor** [comment]
Need more context for feedback–where is this being published? Who's the target audience? ("Managers" is really really really broad)

**Comment by snuggs** [comment]
Well in my experience "Hiring manager" has ranged from A recruiter, to more boutique as in how @joyceschiffer operates. To say my previous position as CTO where I had to hire people internally like @mrbernnz and @btakita. Great question. And I don't have a solid answer. Let's remember the theme that Joyce and @melaniegershman mentioned was *communication*. The "roles" seem to fluctuate per person.  Great feedback @mcantor. Curious to @brandondees opinion as he has hired before.

What closes this issue is what is OUR definition of what that role should be accountable for. Same with Junior/Senior. No overthinking. Just the fact we are shedding light on the matter is important.

**Comment by brandondees** [comment]
Maybe I'm missing some context, so I don't know what the goal or deliverable for this issue is. I like the theme of discussion though.

As for junior/senior developers, I am not in favor of continuing to use those terms at all. There's way too much baggage and too much "it depends" which we'd just be adding to to try to continue adding meaning to those.

As for "who is a hiring manager?" -- it's once again "it depends," contingent on a lot of circumstances for a given organization, or at least I presume. What _should_ a hiring manager be/do? I don't know, I'm just beginning to try to figure out how to hire and manage effectively myself. It's not as if I have any real experience or training in the matter. I think someone who hires for technical roles should have a good level of understanding of the work involved. They should be a hub of communication between team members and between teams (I think). They should be accountable for communication issues within their team, and provide accountability to their team members.

**Comment by snuggs** [comment]
I like it @brandondees . A statement to the community if you will. As we will be going over these at NYC.rb, Paris.rb, @janz93's meetup in Germany, Miami.rb, hopefully spread the new word in ATL.rb, and LA.rb. Similar to how Kent C. Dodds has "All Contributors" Which is doing well. Sometimes terms NEED to be redifined in the community. At minimum it will be a couple paragraphs in a "What's your role?" section. On the main site :-) I feel we have enough feedback to put something up. Will make a PR.
